apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: mydb
  name: mydb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mydb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yaml convert
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: mydb
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
            - name: POSTGRES_USER
              value: postgres
          image: postgres:17.5-alpine3.22
          name: microservice-db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-vol
            - mountPath: /docker-entrypoint-initdb.d/initdb.sh
              name: mydb-cm1
              readOnly: true
              subPath: initdb.sh
      restartPolicy: Always
      volumes:
        - name: db-vol
          persistentVolumeClaim:
            claimName: db-vol
        - configMap:
            items:
              - key: initdb.sh
                path: initdb.sh
            name: mydb-cm1
          name: mydb-cm1
