---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-deployment
  labels:
    app: book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
        - name: book-ms
          image: filipposavarese/book:1.0-SNAPSHOT
          ports:
          - containerPort: 8122
          volumeMounts:
          - mountPath: /app/config
            readOnly: true
            name: book-conf
      volumes:
      - name: book-conf
        configMap:
          name: book-conf
          items:
            - key: application.properties
              path: application.properties
---
apiVersion: v1
kind: Service
metadata:
  name: book-service
  labels:
    app: book
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 32104
      port: 8122
      targetPort: 8122
  selector:
    app: book
---
apiVersion: v1
kind: ConfigMap
data:
  application.properties: |-
    #Local MongoDB config
    spring.data.mongodb.authentication-database=admin
    spring.data.mongodb.username=root
    spring.data.mongodb.password=root
    spring.data.mongodb.database=book_db
    spring.data.mongodb.port=27017
    spring.data.mongodb.host=book-mongodb

    # App config
    server.port=8122
    spring.application.name=BookMicroservice
    server.servlet.context-path=/books-service

    # Log config
    logging.level.org.springframework.web.servlet.DispatcherServlet=TRACE

    # Management config
    management.endpoint.info.enabled=true
    management.security.enabled=false
metadata:
  name: book-conf
  namespace: default